
//diferentes niveles del proceso de pensamiento
const Verbos = {
    Aplicar: "Usar conocimientos en la práctica o resolución de problemas. --Verbo de Aplicación--,--Verbo para Objetivo General--",
    Analizar: "Examinar en profundidad los componentes de un tema. --Verbo de Análisis--,--Verbo para Objetivo General--",
    Calificar: "Asignar un valor o puntuación a un desempeño. --Verbo de Evaluación--,--Verbo para Objetivo General--",
    Categorizar: "Asignar conceptos a grupos definidos. --Verbo de Análisis--,--Verbo para Objetivo General--",
    Clasificar: "Agrupar elementos según sus características. --Verbo de Análisis--",
    Comparar: "Examinar similitudes y diferencias. --Verbo de Comprensión--,--Verbo para Objetivo General--",
    Construir: "Elaborar algo tangible o conceptual. --Verbo de Síntesis--",
    Constatar: "Verificar mediante observación directa. --Verbo de Análisis--",
    Criticar: "Evaluar señalando aspectos positivos y negativos. --Verbo de Evaluación--",
    Debatir: "Contraponer ideas con argumentos. --Verbo de Evaluación--",
    Definir: "Indicar el significado exacto de un término. --Verbo de Conocimiento--,--Verbo para Objetivo General--",
    Describir: "Explicar las características o detalles de algo. --Verbo de Comprensión--,--Verbo para Objetivo General--",
    Dibujar: "Representar gráficamente ideas o conceptos. --Verbo de Aplicación--",
    Diferenciar: "Establecer cómo se distingue un elemento respecto a otro. --Verbo de Análisis--",
    Dirigir: "Coordinar un proceso hacia una meta. --Verbo de Síntesis--,--Verbo para Objetivo General--",
    Diseñar: "Elaborar una estructura, esquema o modelo original. --Verbo de Síntesis--,--Verbo para Objetivo General--",
    Discutir: "Exponer ideas o argumentos sobre un tema. --Verbo de Evaluación--",
    Distinguir: "Señalar diferencias entre elementos. --Verbo de Análisis--,--Verbo para Objetivo General--",
    Dramatizar: "Representar una situación mediante acciones. --Verbo de Aplicación--",
    Emplear: "Hacer uso de un recurso o conocimiento. --Verbo de Aplicación--",
    Esbozar: "Hacer un esquema general sin detalles. --Verbo de Aplicación--",
    Establecer: "Determinar una base o principio. --Verbo de Síntesis--,--Verbo para Objetivo General--",
    Estimar: "Calcular de forma aproximada el valor o efecto de algo. --Verbo de Evaluación--,--Verbo para Objetivo General--",
    Examinar: "Observar algo con atención y detalle. --Verbo de Análisis--,--Verbo para Objetivo General--",
    Explicar: "Aclarar algo proporcionando razones o ejemplos. --Verbo de Comprensión--,--Verbo para Objetivo General--",
    Expresar: "Comunicar ideas en una situación concreta. --Verbo de Aplicación--,--Verbo para Objetivo General--",
    Formular: "Expresar con claridad una idea o hipótesis. --Verbo de Síntesis--,--Verbo para Objetivo General--",
    Identificar: "Nombrar o determinar algo entre opciones. --Verbo de Conocimiento--,--Verbo para Objetivo General--",
    Ilustrar: "Aclarar una idea mediante ejemplos o gráficos. --Verbo de Aplicación--",
    Informar: "Comunicar datos con precisión. --Verbo de Comprensión--",
    Interpretar: "Explicar el sentido de algo usando palabras propias. --Verbo de Comprensión--,--Verbo para Objetivo General--",
    Medir: "Cuantificar una característica según una escala. --Verbo de Evaluación--",
    Memorizar: "Aprender algo de manera literal. --Verbo de Conocimiento--",
    Organizar: "Disponer en orden lógico elementos. --Verbo de Síntesis--,--Verbo para Objetivo General--",
    Operar: "Ejecutar un proceso o mecanismo. --Verbo de Aplicación--",
    Planear: "Organizar acciones para alcanzar un objetivo. --Verbo de Síntesis--,--Verbo para Objetivo General--",
    Preparar: "Disponer elementos para una actividad futura. --Verbo de Síntesis--,--Verbo para Objetivo General--",
    Probar: "Verificar si algo funciona correctamente o es verdadero. --Verbo de Evaluación--,--Verbo para Objetivo General--",
    Proponer: "Sugerir una idea, plan o solución. --Verbo de Síntesis--,--Verbo para Objetivo General--",
    Reconocer: "Identificar algo previamente aprendido. --Verbo de Conocimiento--",
    Registrar: "Anotar o dejar constancia escrita. --Verbo de Conocimiento--,--Verbo para Objetivo General--",
    Relatar: "Narrar un evento con orden lógico. --Verbo de Comprensión--,--Verbo para Objetivo General--",
    Repetir: "Reproducir algo memorizado. --Verbo de Conocimiento--",
    Reunir: "Juntar elementos o datos para un propósito común. --Verbo de Síntesis--",
    Revisar: "Analizar nuevamente algo para mejorar. --Verbo de Comprensión--",
    Subrayar: "Resaltar información importante. --Verbo de Conocimiento--",
    Traducir: "Expresar una idea en forma diferente o más clara. --Verbo de Comprensión--",
    Ubicar: "Situar algo en un espacio o concepto. --Verbo de Comprensión--",
    Utilizar: "Poner en práctica herramientas o conceptos. --Verbo de Aplicación--",
    Valorar: "Reconocer la importancia o calidad de algo. --Verbo de Evaluación--",
    Juzgar: "Formar una opinión crítica basada en evidencias. --Verbo de Evaluación--",
}


export const verbosArray = Object.entries(Verbos).map(([key, value]) => ({
    palabra: key,
    descripcion: value
  }));
